#! /bin/bash
# shellcheck disable=SC2207 # Arrays are a pain in bash 3

echo "functions assume they are run from repo root"

run_local(){
    echo "Running locally inside Railway shell"
    railway shell << EOF
    source venv/bin/activate
    PGHOST=junction.proxy.rlwy.net PGPORT=59857 python main.py
    deactivate
EOF
}

run_cleanup(){
    echo "Running cleanup script"
    railway shell << EOF
    source venv/bin/activate
    PGHOST=junction.proxy.rlwy.net PGPORT=59857 python cron/cleanup.py
    deactivate
EOF
}

clear_all_attempts(){
    echo "Clearing all attempts"
    railway shell << EOF
    source venv/bin/activate
    PGHOST=junction.proxy.rlwy.net PGPORT=59857 python cron/cleanup.py --clear-all
    deactivate
EOF
}
